In [17]:
list = ['2019/02012019.pdf', '2019/03012019.pdf', '2019/04012019.pdf', '2019/05012019.pdf', '2019/07012019.pdf', '2019/08012019.pdf', '2019/09012019.pdf', '2019/10012019.pdf', '2019/11012019.pdf', '2019/12012019.pdf', '2019/14012019.pdf', '2019/15012019.pdf', '2019/16012019.pdf', '2019/17012019.pdf', '2019/18012019.pdf', '2019/19012019.pdf', '2019/21012019.pdf', '2019/22012019.pdf', '2019/23012019.pdf', '2019/24012019.pdf', '2019/25012019.pdf', '2019/28012019.pdf', '2019/29012019.pdf', '2019/30012019.pdf', '2019/31012019.pdf', '2019/01022019.pdf', '2019/02022019.pdf', '2019/04022019.pdf', '2019/05022019.pdf', '2019/06022019.pdf', '2019/07022019.pdf', '2019/08022019.pdf', '2019/09022019.pdf', '2019/11022019.pdf', '2019/12022019.pdf', '2019/13022019.pdf', '2019/14022019.pdf', '2019/15022019.pdf', '2019/16022019.pdf', '2019/18022019.pdf', '2019/19022019.pdf', '2019/20022019.pdf', '2019/21022019.pdf', '2019/22022019.pdf', '2019/23022019.pdf', '2019/25022019.pdf', '2019/26022019.pdf', '2019/27022019.pdf', '2019/28022019.pdf', '2019/01032019.pdf', '2019/02032019.pdf', '2019/04032019.pdf', '2019/05032019.pdf', '2019/06032019.PDF', '2019/07022019.pdf', '2019/08032019.pdf', '2019/09032019.pdf', '2019/11032019.pdf', '2019/12032019.pdf', '2019/13032019.pdf', '2019/15032019.pdf', '2019/18032019.pdf', '2019/19032019.pdf', '2019/20032019.pdf', '2019/22032019.pdf', '2019/23032019.pdf', '2019/25022019.pdf', '2019/26032019.pdf', '2019/27032019.pdf', '2019/28032019.pdf', '2019/29032019.pdf', '2019/30032019.pdf', '2019/01042019.pdf', '2019/02042019.PDF', '2019/03042019.PDF', '2019/04042019.pdf', '2019/05042019.pdf', '2019/06042019.pdf', '2019/08042019.pdf', '2019/09042019.pdf', '2019/10042019.pdf', '2019/11042019.pdf', '2019/12042019.pdf', '2019/13042019.pdf', '2019/15042019.pdf', '2019/16042019.pdf', '2019/17042019.pdf', '2019/18042019.pdf', '2019/19042019.pdf', '2019/20042019.pdf', '2019/22042019.pdf', '2019/23042019.pdf', '2019/24042019.pdf', '2019/25042019.pdf', '2019/26042019.pdf', '2019/27042019.pdf', '2019/29042019.pdf', '2019/30042019.pdf', '2019/01052019.pdf', '2019/02052019.pdf', '2019/03052019.pdf', '2019/04052019.pdf', '2019/06052019.pdf', '2019/07052019.pdf', '2019/08052019.pdf', '2019/09052019.pdf', '2019/10052019.pdf', '2019/11052019.pdf', '2019/13052019.pdf', '2019/14052019.pdf', '2019/15052019.pdf', '2019/16052019.pdf', '2019/17052019.pdf', '2019/18052019.pdf', '2019/20052019.pdf', '2019/21052019.pdf', '2019/22052019.pdf', '2019/23052019.pdf', '2019/24052019.pdf', '2019/25052019.pdf', '2019/27052019.pdf', '2019/28052019.pdf', '2019/29052019.pdf', '2019/30052019.pdf', '2019/31052019.pdf', '2019/01062019.pdf', '2019/03062019.pdf', '2019/04062019.pdf', '2019/05062019.pdf', '2019/06062019.pdf', '2019/07062019.pdf', '2019/08062019.pdf', '2019/10062019.pdf', '2019/11062019.pdf', '2019/12062019.pdf', '2019/13062019.pdf', '2019/14062019.pdf', '2019/15062019.pdf', '2019/17062019.pdf', '2019/18062019.pdf', '2019/19062019.pdf', '2019/20062019.pdf', '2019/21062019.pdf', '2019/22062019.pdf', '2019/24062019.pdf', '2019/25062019.pdf', '2019/26062019.pdf', '2019/27062019.pdf', '2019/28062019.pdf', '2019/29062019.pdf', '2019/01072019.pdf', '2019/02072019.pdf', '2019/03072019.pdf', '2019/04072019.pdf', '2019/05072019.pdf', '2019/06072019.pdf', '2019/08072019.pdf', '2019/09072019.pdf', '2019/10072019.pdf', '2019/11072019.pdf', '2019/12072019.pdf', '2019/13072019.pdf', '2019/15072019.pdf', '2019/16072019.pdf', '2019/17072019.pdf', '2019/18072019.pdf', '2019/19072019.pdf', '2019/20072019.pdf', '2019/22072019.pdf', '2019/23072019.pdf', '2019/24072019.pdf', '2019/25072019.pdf', '2019/26072019.pdf', '2019/27072019.pdf', '2019/29072019.pdf', '2019/31072019.pdf', '2019/01082019.pdf', '2019/02082019.pdf', '2019/03082019.pdf', '2019/05082019.pdf', '2019/06082019.pdf', '2019/07082019.pdf', '2019/08082019.pdf', '2019/09082019.pdf', '2019/10082019.pdf', '2019/12082019.pdf', '2019/13082019.pdf', '2019/14082019.pdf', '2019/16082019.pdf', '2019/17082019.pdf', '2019/19082019.pdf', '2019/20082019.pdf', '2019/21082019.pdf', '2019/22082019.pdf', '2019/23082019.pdf', '2019/24092019.pdf', '2019/26092019.pdf', '2019/27082019.PDF', '2019/28082019.pdf', '2019/30082019.pdf', '2019/31082019.pdf', '2019/02092019.pdf', '2019/03092019.pdf', '2019/04092019.pdf', '2019/05092019.pdf', '2019/06092019.pdf', '2019/07092019.pdf', '2019/09092019.pdf', '2019/10092019.pdf', '2019/11092019.pdf', '2019/12092019.pdf', '2019/13092019.pdf', '2019/14092019.pdf', '2019/16092019.pdf', '2019/17092019.pdf', '2019/18092019.pdf', '2019/19092019.pdf', '2019/20092019.pdf', '2019/21092019.pdf', '2019/23092019.pdf', '2019/24092019.pdf', '2019/25092019.pdf', '2019/26092019.pdf', '2019/27092019.pdf', '2019/28092019.pdf', '2019/30092019.pdf', '2019/01102019.pdf', '2019/03102019.pdf', '2019/04102019.pdf', '2019/07102019.pdf', '2019/08102019.pdf', '2019/09102019.pdf', '2019/10102019.pdf', '2019/11102019.pdf', '2019/12102019.pdf', '2019/14102019.pdf', '2019/15102019.pdf', '2019/16102019.PDF', '2019/17102019.pdf', '2019/18102019.pdf', '2019/19102019.pdf', '2019/21102019.pdf', '2019/22102019.pdf', '2019/23102019.pdf', '2019/24102019.pdf', '2019/25102019.pdf', '2019/26102019.pdf', '2019/29102019.pdf', '2019/30102019.pdf', '2019/31102019.pdf', '2019/01112019.pdf', '2019/02112019.pdf', '2019/04112019.pdf', '2019/05112019.pdf', '2019/06112019.pdf', '2019/07112019.pdf', '2019/08112019.pdf', '2019/09112019.pdf', '2019/11112019.pdf', '2019/12112019.pdf', '2019/13112019.pdf', '2019/14112019.pdf', '2019/16112019.pdf', '2019/18112019.pdf', '2019/19112019.pdf', '2019/20112019.pdf', '2019/21112019.pdf', '2019/22112019.pdf', '2019/25112019.pdf', '2019/26112019.pdf', '2019/27112019.pdf', '2019/28112019.pdf', '2019/29112019.pdf', '2019/30112019.pdf', '2019/02122019.pdf', '2019/03122019.pdf', '2019/04122019.pdf', '2019/05122019.pdf', '2019/06122019.pdf', '2019/07122019.pdf', '2019/09122019.pdf', '2019/10122019.pdf', '2019/11122019.pdf', '2019/12122019.pdf', '2019/13122019.pdf', '2019/14122019.pdf', '2019/16122019.pdf', '2019/17122019.pdf', '2019/18122019.pdf', '2019/19122019.pdf', '2019/21122019.pdf', '2019/23122019.pdf', '2019/24122019.pdf', '2019/25122019.pdf', 
        '2019/26122019.pdf', '2019/27122019.pdf', '2019/28122019.pdf', '2019/30122019.pdf', '2019/31122019.pdf']

In [18]:
import camelot
import pandas as pd
import datetime

In [19]:
tables = camelot.read_pdf("01012019.pdf", pages="1,2")
df = tables[0].df[10:]
df2 = tables[1].df[1:]
df = pd.concat([df, df2], axis=0)

In [20]:
df

,0,1,2,3,4,5,6,7,8,9,10
10,NO. COMM. & STATE,IN TONS,,,IN KG.,,PACKING SIZE,,MINI,MAXI,MODAL
11,1,APPLE\n1829.6,,,,,,,,,
12,,HPS/KINNAUR/SHIMLA(CS),,ROYAL DEL.,10,KG.,C.BOX,A,800,1100,1000
13,,,,,10,KG.,C.BOX,B,600,700,650
14,,KULLU/CS,,ROYAL DEL.,16,KG.,C.BOX,A,850,1000,900
...,...,...,...,...,...,...,...,...,...,...,...
61,18,PAPAYA,279.1,,,,,,,,
62,,KAR/AP/UP/MP/MAH,,DISCO,40,KG.,LOOSE,A,350,440,400
63,,,,,40,KG.,LOOSE,B,260,340,300
64,,,,,40,KG.,LOOSE,C,200,240,220
65,19,PINE.APPLE,71.1,,,,,,,,

In [21]:
df.columns =['S','NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']

In [22]:
df = df.drop(df.index[0])

In [23]:
# df = df.drop(['S', 'ARRIVAL_IN_TONS', 'KG'], axis=1)

In [24]:
df['Date'] = "01012019"

/Users/sakshamarora/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [25]:
df

,S,NAME,ARRIVAL_IN_TONS,VARIETY,WEIGHT_IN_KG,KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE,Date
11,1,APPLE\n1829.6,,,,,,,,,,01012019
12,,HPS/KINNAUR/SHIMLA(CS),,ROYAL DEL.,10,KG.,C.BOX,A,800,1100,1000,01012019
13,,,,,10,KG.,C.BOX,B,600,700,650,01012019
14,,KULLU/CS,,ROYAL DEL.,16,KG.,C.BOX,A,850,1000,900,01012019
15,,,,,16,KG.,C.BOX,B,625,800,700,01012019
...,...,...,...,...,...,...,...,...,...,...,...,...
61,18,PAPAYA,279.1,,,,,,,,,01012019
62,,KAR/AP/UP/MP/MAH,,DISCO,40,KG.,LOOSE,A,350,440,400,01012019
63,,,,,40,KG.,LOOSE,B,260,340,300,01012019
64,,,,,40,KG.,LOOSE,C,200,240,220,01012019
65,19,PINE.APPLE,71.1,,,,,,,,,01012019

In [26]:
df = df.reset_index(drop=True)

In [27]:
idx_start = df.index[df['NAME'] == 'BANANA']
idx_start = idx_start[0]
idx_end = df.index[df['NAME'] == 'R.BER']
idx_end = idx_end[0]

65

In [28]:
df = df[idx_start:idx_end]

In [29]:
df

,S,NAME,ARRIVAL_IN_TONS,VARIETY,WEIGHT_IN_KG,KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE,Date
39,5,BANANA,15.1,,,,,,,,,01012019
40,,GUJ/MP/AP/SAWDA/JALGAON,,,100,KG.,LOOSE,A,1000,1100,1050,01012019
41,,,,,100,KG.,LOOSE,B,850,950,900,01012019
42,,,,,100,KG.,LOOSE,C,700,840,800,01012019

In [39]:
for item in list:
    print(item[5:])
    table = camelot.read_pdf(item[5:], pages="1,2")
    df1 = table[0].df[10:]
    df3 = table[1].df[1:]
    df1.columns =['S', 'NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']
    df1 = df1.reset_index(drop=True)
    next = 'R.BER' if 'R.BER' in df1.NAME.values else 'BAILGIRI'
    print(next)
    idx_start = df1.index[df1['NAME'].str.contains('BANANA')]
    idx_start = idx_start[0]
    idx_end = df1.index[df1['NAME'].str.contains(next)]
    idx_end = idx_end[0]
    df1 = df1[idx_start:idx_end]
    df1 = df1.drop(df1.index[0])
#     df1 = df1.drop(['ARRIVAL_IN_TONS', 'KG'], axis=1)
    df1['Date'] = item[5:13]
    df = pd.concat([df, df1], axis=0)

02012019.pdf
R.BER
03012019.pdf
R.BER
04012019.pdf
R.BER
05012019.pdf
R.BER
07012019.pdf
R.BER
08012019.pdf
R.BER
09012019.pdf
R.BER
10012019.pdf
R.BER
11012019.pdf
R.BER
12012019.pdf
R.BER
14012019.pdf
R.BER
15012019.pdf
R.BER
16012019.pdf
R.BER
17012019.pdf
R.BER
18012019.pdf
R.BER
19012019.pdf
R.BER
21012019.pdf
R.BER
22012019.pdf
R.BER
23012019.pdf
R.BER
24012019.pdf
R.BER
25012019.pdf
R.BER
28012019.pdf
R.BER
29012019.pdf
R.BER
30012019.pdf
R.BER
31012019.pdf
R.BER
01022019.pdf
R.BER
02022019.pdf
R.BER
04022019.pdf
R.BER
05022019.pdf
R.BER
06022019.pdf
R.BER
07022019.pdf
R.BER
08022019.pdf
R.BER
09022019.pdf
R.BER
11022019.pdf
R.BER
12022019.pdf
R.BER
13022019.pdf
R.BER
14022019.pdf
R.BER
15022019.pdf
R.BER
16022019.pdf
R.BER
18022019.pdf
R.BER
19022019.pdf
R.BER
20022019.pdf
R.BER
21022019.pdf
R.BER
22022019.pdf
R.BER
23022019.pdf
R.BER
25022019.pdf
R.BER
26022019.pdf
R.BER
27022019.pdf
R.BER
28022019.pdf
R.BER
01032019.pdf
R.BER
02032019.pdf
R.BER
04032019.pdf
R.BER
05032019.pdf
R.BER
06032019.PDF
R.BER
07022019.pdf
R.BER
08032019.pdf
R.BER
09032019.pdf
R.BER
11032019.pdf
R.BER
12032019.pdf
R.BER
13032019.pdf
R.BER
15032019.pdf
R.BER
18032019.pdf
R.BER
19032019.pdf
R.BER
20032019.pdf
R.BER
22032019.pdf
R.BER
23032019.pdf
R.BER
25022019.pdf
R.BER
26032019.pdf
R.BER
27032019.pdf
R.BER
28032019.pdf
R.BER
29032019.pdf
R.BER
30032019.pdf
R.BER
01042019.pdf
R.BER
02042019.PDF
R.BER
03042019.PDF
R.BER
04042019.pdf
R.BER
05042019.pdf
R.BER
06042019.pdf
R.BER
08042019.pdf
R.BER
09042019.pdf
R.BER
10042019.pdf
R.BER
11042019.pdf
R.BER
12042019.pdf
R.BER
13042019.pdf
R.BER
15042019.pdf
R.BER
16042019.pdf
R.BER
17042019.pdf
R.BER
18042019.pdf
R.BER
19042019.pdf
R.BER
20042019.pdf
R.BER
22042019.pdf
R.BER
23042019.pdf
R.BER
24042019.pdf
R.BER
25042019.pdf
R.BER
26042019.pdf
R.BER
27042019.pdf
R.BER
29042019.pdf
R.BER
30042019.pdf
R.BER
01052019.pdf
R.BER
02052019.pdf
R.BER
03052019.pdf
R.BER
04052019.pdf
R.BER
06052019.pdf
R.BER
07052019.pdf
R.BER
08052019.pdf
R.BER
09052019.pdf
R.BER
10052019.pdf
R.BER
11052019.pdf
R.BER
13052019.pdf
R.BER
14052019.pdf
R.BER
15052019.pdf
R.BER
16052019.pdf
R.BER
17052019.pdf
R.BER
18052019.pdf
R.BER
20052019.pdf
R.BER
21052019.pdf
R.BER
22052019.pdf
R.BER
23052019.pdf
R.BER
24052019.pdf
R.BER
25052019.pdf
R.BER
27052019.pdf
R.BER
28052019.pdf
R.BER
29052019.pdf
R.BER
30052019.pdf
R.BER
31052019.pdf
R.BER
01062019.pdf
R.BER
03062019.pdf
R.BER
04062019.pdf
BAILGIRI
05062019.pdf
BAILGIRI
06062019.pdf
BAILGIRI
07062019.pdf
BAILGIRI
08062019.pdf
BAILGIRI
10062019.pdf
BAILGIRI
11062019.pdf
BAILGIRI
12062019.pdf
BAILGIRI
13062019.pdf
BAILGIRI
14062019.pdf
BAILGIRI
15062019.pdf
BAILGIRI
17062019.pdf
BAILGIRI
18062019.pdf
BAILGIRI
19062019.pdf
R.BER
20062019.pdf
R.BER
21062019.pdf
R.BER
22062019.pdf
R.BER
24062019.pdf
BAILGIRI

IndexError: index 0 is out of bounds for axis 0 with size 0

In [41]:
list2 = ['2019/25062019.pdf', '2019/26062019.pdf', '2019/27062019.pdf', '2019/28062019.pdf', '2019/29062019.pdf', '2019/01072019.pdf', '2019/02072019.pdf', '2019/03072019.pdf', '2019/04072019.pdf', '2019/05072019.pdf', '2019/06072019.pdf', '2019/08072019.pdf', '2019/09072019.pdf', '2019/10072019.pdf', '2019/11072019.pdf', '2019/12072019.pdf', '2019/13072019.pdf', '2019/15072019.pdf', '2019/16072019.pdf', '2019/17072019.pdf', '2019/18072019.pdf', '2019/19072019.pdf', '2019/20072019.pdf', '2019/22072019.pdf', '2019/23072019.pdf', '2019/24072019.pdf', '2019/25072019.pdf', '2019/26072019.pdf', '2019/27072019.pdf', '2019/29072019.pdf', '2019/31072019.pdf', '2019/01082019.pdf', '2019/02082019.pdf', '2019/03082019.pdf', '2019/05082019.pdf', '2019/06082019.pdf', '2019/07082019.pdf', '2019/08082019.pdf', '2019/09082019.pdf', '2019/10082019.pdf', '2019/12082019.pdf', '2019/13082019.pdf', '2019/14082019.pdf', '2019/16082019.pdf', '2019/17082019.pdf', '2019/19082019.pdf', '2019/20082019.pdf', '2019/21082019.pdf', '2019/22082019.pdf', '2019/23082019.pdf', '2019/24092019.pdf', '2019/26092019.pdf', '2019/27082019.PDF', '2019/28082019.pdf', '2019/30082019.pdf', '2019/31082019.pdf', '2019/02092019.pdf', '2019/03092019.pdf', '2019/04092019.pdf', '2019/05092019.pdf', '2019/06092019.pdf', '2019/07092019.pdf', '2019/09092019.pdf', '2019/10092019.pdf', '2019/11092019.pdf', '2019/12092019.pdf', '2019/13092019.pdf', '2019/14092019.pdf', '2019/16092019.pdf', '2019/17092019.pdf', '2019/18092019.pdf', '2019/19092019.pdf', '2019/20092019.pdf', '2019/21092019.pdf', '2019/23092019.pdf', '2019/24092019.pdf', '2019/25092019.pdf', '2019/26092019.pdf', '2019/27092019.pdf', '2019/28092019.pdf', '2019/30092019.pdf', '2019/01102019.pdf', '2019/03102019.pdf', '2019/04102019.pdf', '2019/07102019.pdf', '2019/08102019.pdf', '2019/09102019.pdf', '2019/10102019.pdf', '2019/11102019.pdf', '2019/12102019.pdf', '2019/14102019.pdf', '2019/15102019.pdf', '2019/16102019.PDF', '2019/17102019.pdf', '2019/18102019.pdf', '2019/19102019.pdf', '2019/21102019.pdf', '2019/22102019.pdf', '2019/23102019.pdf', '2019/24102019.pdf', '2019/25102019.pdf', '2019/26102019.pdf', '2019/29102019.pdf', '2019/30102019.pdf', '2019/31102019.pdf', '2019/01112019.pdf', '2019/02112019.pdf', '2019/04112019.pdf', '2019/05112019.pdf', '2019/06112019.pdf', '2019/07112019.pdf', '2019/08112019.pdf', '2019/09112019.pdf', '2019/11112019.pdf', '2019/12112019.pdf', '2019/13112019.pdf', '2019/14112019.pdf', '2019/16112019.pdf', '2019/18112019.pdf', '2019/19112019.pdf', '2019/20112019.pdf', '2019/21112019.pdf', '2019/22112019.pdf', '2019/25112019.pdf', '2019/26112019.pdf', '2019/27112019.pdf', '2019/28112019.pdf', '2019/29112019.pdf', '2019/30112019.pdf', '2019/02122019.pdf', '2019/03122019.pdf', '2019/04122019.pdf', '2019/05122019.pdf', '2019/06122019.pdf', '2019/07122019.pdf', '2019/09122019.pdf', '2019/10122019.pdf', '2019/11122019.pdf', '2019/12122019.pdf', '2019/13122019.pdf', '2019/14122019.pdf', '2019/16122019.pdf', '2019/17122019.pdf', '2019/18122019.pdf', '2019/19122019.pdf', '2019/21122019.pdf', '2019/23122019.pdf', '2019/24122019.pdf', '2019/25122019.pdf', 
        '2019/26122019.pdf', '2019/27122019.pdf', '2019/28122019.pdf', '2019/30122019.pdf', '2019/31122019.pdf']

In [58]:
for item in list2:
    print(item[5:])
    table = camelot.read_pdf(item[5:], pages="1,2")
    df1 = table[0].df[10:]
    df3 = table[1].df[1:]
    df1 = pd.concat([df1,df3], axis=0)
    df1.columns =['S', 'NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']
    df1 = df1.reset_index(drop=True)
    next = 'R.BER' if 'R.BER' in df1.NAME.values else 'BAILGIRI'
    print(next)
    idx_start = df1.index[df1['NAME'].str.contains('BANANA')]
    idx_start = idx_start[0]
    idx_end = df1.index[df1['NAME'].str.contains(next)]
    idx_end = idx_end[0]
    df1 = df1[idx_start:idx_end]
    df1 = df1.drop(df1.index[0])
#     df1 = df1.drop(['ARRIVAL_IN_TONS', 'KG'], axis=1)
    df1['Date'] = item[5:13]
    df = pd.concat([df, df1], axis=0)

25062019.pdf
R.BER
26062019.pdf
R.BER
27062019.pdf
R.BER
28062019.pdf
R.BER
29062019.pdf
R.BER
01072019.pdf
R.BER
02072019.pdf
R.BER
03072019.pdf
R.BER
04072019.pdf
R.BER
05072019.pdf
R.BER
06072019.pdf
R.BER
08072019.pdf
R.BER
09072019.pdf
R.BER
10072019.pdf
R.BER
11072019.pdf
R.BER
12072019.pdf
R.BER
13072019.pdf
R.BER
15072019.pdf
R.BER
16072019.pdf
R.BER
17072019.pdf
R.BER
18072019.pdf
R.BER
19072019.pdf
R.BER
20072019.pdf
R.BER
22072019.pdf
R.BER
23072019.pdf
R.BER
24072019.pdf
R.BER
25072019.pdf
R.BER
26072019.pdf
R.BER
27072019.pdf
R.BER
29072019.pdf
R.BER
31072019.pdf
R.BER
01082019.pdf
R.BER
02082019.pdf
R.BER
03082019.pdf
R.BER
05082019.pdf
R.BER
06082019.pdf
R.BER
07082019.pdf
R.BER
08082019.pdf
R.BER
09082019.pdf
R.BER
10082019.pdf
R.BER
12082019.pdf
R.BER
13082019.pdf
R.BER
14082019.pdf
R.BER
16082019.pdf
R.BER
17082019.pdf
R.BER
19082019.pdf
R.BER
20082019.pdf
R.BER
21082019.pdf
R.BER
22082019.pdf
R.BER
23082019.pdf
R.BER
24092019.pdf
R.BER
26092019.pdf
R.BER
27082019.PDF
R.BER
28082019.pdf
R.BER
30082019.pdf
R.BER
31082019.pdf
R.BER
02092019.pdf
R.BER
03092019.pdf
R.BER
04092019.pdf
R.BER
05092019.pdf
R.BER
06092019.pdf
R.BER
07092019.pdf
R.BER
09092019.pdf
R.BER
10092019.pdf
R.BER
11092019.pdf
R.BER
12092019.pdf
R.BER
13092019.pdf
R.BER
14092019.pdf
R.BER
16092019.pdf
R.BER
17092019.pdf
R.BER
18092019.pdf
R.BER
19092019.pdf
R.BER
20092019.pdf
R.BER
21092019.pdf
R.BER
23092019.pdf
R.BER
24092019.pdf
R.BER
25092019.pdf
R.BER
26092019.pdf
R.BER
27092019.pdf
R.BER
28092019.pdf
R.BER
30092019.pdf
R.BER
01102019.pdf
R.BER
03102019.pdf
R.BER
04102019.pdf
R.BER
07102019.pdf
R.BER
08102019.pdf
R.BER
09102019.pdf
R.BER
10102019.pdf
R.BER
11102019.pdf
R.BER
12102019.pdf
R.BER
14102019.pdf
R.BER
15102019.pdf
R.BER
16102019.PDF
R.BER
17102019.pdf
R.BER
18102019.pdf
R.BER
19102019.pdf
R.BER
21102019.pdf
R.BER
22102019.pdf
R.BER
23102019.pdf
R.BER
24102019.pdf
R.BER
25102019.pdf
R.BER
26102019.pdf
R.BER
29102019.pdf
R.BER
30102019.pdf
R.BER
31102019.pdf
R.BER
01112019.pdf
R.BER
02112019.pdf
R.BER
04112019.pdf
R.BER
05112019.pdf
R.BER
06112019.pdf
R.BER
07112019.pdf
R.BER
08112019.pdf
R.BER
09112019.pdf
R.BER
11112019.pdf
R.BER
12112019.pdf
R.BER
13112019.pdf
R.BER
14112019.pdf
R.BER
16112019.pdf
R.BER
18112019.pdf
R.BER
19112019.pdf
R.BER
20112019.pdf
R.BER
21112019.pdf
R.BER
22112019.pdf
R.BER
25112019.pdf
R.BER
26112019.pdf
R.BER
27112019.pdf
R.BER
28112019.pdf
R.BER
29112019.pdf
R.BER
30112019.pdf
R.BER
02122019.pdf
R.BER
03122019.pdf
R.BER
04122019.pdf
R.BER
05122019.pdf
R.BER
06122019.pdf
R.BER
07122019.pdf
R.BER
09122019.pdf
R.BER
10122019.pdf
R.BER
11122019.pdf
R.BER
12122019.pdf
R.BER
13122019.pdf
R.BER
14122019.pdf
R.BER
16122019.pdf
R.BER
17122019.pdf
R.BER
18122019.pdf
R.BER
19122019.pdf
R.BER
21122019.pdf
R.BER
23122019.pdf
R.BER
24122019.pdf
R.BER
25122019.pdf
R.BER
26122019.pdf
R.BER
27122019.pdf
R.BER
28122019.pdf
R.BER
30122019.pdf
R.BER
31122019.pdf
R.BER

In [43]:
tabl = camelot.read_pdf("16072019.pdf", pages="1,2")
df5 = tabl[0].df[10:]
df6 = tabl[1].df[1:]
df5 = pd.concat([df5,df6], axis=0)

In [46]:
df6.columns =['S','NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']

In [47]:
df6

,S,NAME,ARRIVAL_IN_TONS,VARIETY,WEIGHT_IN_KG,KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE
1,NO.,COMM. & STATE\nIN TONS,,,IN KG.,,PACKING SIZE,,MINI,MAXI,MODAL
2,,,,,20,KG.,C.BOX,B,1000,1300,1100
3,,,,,20,KG.,C.BOX,C,500,900,700
4,7,BANANA\n12.5,,,,,,,,,
5,,GUJ/MP/AP/SAWDA/JALGAON,,,100,KG.,LOOSE,A,1100,1300,1200
...,...,...,...,...,...,...,...,...,...,...,...
60,,,,,8,KG,C.BOX,C,80,160,125
61,,,,CHAND,8,KG,C.BOX,A,100,160,140
62,,,,,8,KG,C.BOX,B,70,90,80
63,19,MANGO,2551.9,,,,,,,,
64,,,,CHAUSA,1,KG,C.BOX,A,40,50,44

In [52]:
idx = df6.index[df6["NAME"].str.contains("BANANA")]

,S,NAME,ARRIVAL_IN_TONS,VARIETY,WEIGHT_IN_KG,KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE
1,NO.,COMM. & STATE\nIN TONS,,,IN KG.,,PACKING SIZE,,MINI,MAXI,MODAL
2,,,,,20,KG.,C.BOX,B,1000,1300,1100
3,,,,,20,KG.,C.BOX,C,500,900,700
4,7,BANANA\n12.5,,,,,,,,,

In [59]:
df.to_excel("bananas2019.xlsx")