In [23]:
list = ['2020/02012020.pdf', '2020/04012020.pdf', '2020/06012020.pdf', '2020/07012020.pdf', '2020/08012020.pdf', '2020/09012020.pdf', '2020/10012020.pdf', '2020/11012020.pdf', '2020/13012020.pdf', '2020/14012020.pdf', '2020/15012020.pdf', '2020/16012020.pdf', '2020/17012020.pdf', '2020/18012020.pdf', '2020/20012020.pdf', '2020/21012020.pdf', '2020/22012020.pdf', '2020/23012020.pdf', '2020/24012020.pdf', '2020/25012020.pdf', '2020/27012020.pdf', '2020/28012020.pdf', '2020/29012020.pdf', '2020/30012020.pdf', '2020/31012020.pdf', '2020/01022020.pdf', '2020/03022020.pdf', '2020/04022020.pdf', '2020/05022020.pdf', '2020/06022020.pdf', '2020/07022020.pdf', '2020/09022020.pdf', '2020/10022020.pdf', '2020/11022020.pdf', '2020/12022020.pdf', '2020/13022020.pdf', '2020/14022020.pdf', '2020/15022020.pdf', '2020/17022020.pdf', '2020/18022020.pdf', '2020/19022020.pdf', '2020/20022020.pdf', '2020/21022020.pdf', '2020/24022020.pdf', '2020/25022020.pdf', '2020/26022020.pdf', '2020/27022020.pdf', '2020/28022020.pdf', '2020/29022020.pdf', '2020/03032020.pdf', '2020/04032020.pdf', '2020/05032020.pdf', '2020/06032020.pdf', '2020/07032020.pdf', '2020/09032020.pdf', '2020/11032020.pdf', '2020/12022020.pdf', '2020/13032020.pdf', '2020/16032020.pdf', '2020/17032020.pdf', '2020/18032020.pdf', '2020/19032020.pdf', '2020/20032020.pdf', '2020/21032020.pdf', '2020/23032020.pdf', '2020/24032020.pdf', '2020/25032020.pdf', '2020/26032020.pdf', '2020/27032020.pdf', '2020/28032020.PDF', '2020/30032020.pdf', '2020/31032020.pdf', '2020/01042020.pdf', '2020/02042020.pdf', '2020/03042020.pdf', '2020/04042020.pdf', '2020/06042020.pdf', '2020/07042020.pdf', '2020/08042020.pdf', '2020/09042020.pdf', '2020/10042020.pdf', '2020/11042020.pdf', '2020/13042020.pdf', '2020/14042020.pdf', '2020/15042020.pdf', '2020/16042020.pdf', '2020/17042020.pdf', '2020/18042020.PDF', '2020/20042020.pdf', '2020/21042020.pdf', '2020/22042020.pdf', '2020/23042020.pdf', '2020/24042020.pdf', '2020/25042020.pdf', '2020/27042020.pdf', '2020/28042020.pdf', '2020/28042020.pdf', '2020/30042020.pdf', '2020/01052020.pdf', '2020/02052020.pdf', '2020/04052020.pdf', '2020/05052020.pdf', '2020/06052020.pdf', '2020/07052020.pdf', '2020/08052020.PDF', '2020/09052020.pdf', '2020/11052020.pdf', '2020/12052020.pdf', '2020/13052020.pdf', '2020/15052020.pdf', '2020/18052020.pdf', '2020/19052020.pdf', '2020/20052020.pdf', '2020/21052020.pdf', '2020/22052020.pdf', '2020/23052020.pdf', '2020/25052020.pdf', '2020/26052020.pdf', '2020/27052020.pdf', '2020/28052020.pdf', '2020/29052020.pdf', '2020/30052020.pdf', '2020/01062020.pdf', '2020/02062020.pdf', '2020/03062020.pdf', '2020/04062020.pdf', '2020/05062020.pdf', '2020/06062020.pdf', '2020/08062020.pdf', '2020/09062020.pdf', '2020/10062020.pdf', '2020/11062020.pdf', '2020/12062020.pdf', '2020/13062020.pdf', '2020/15062020.pdf', '2020/16062020.pdf', '2020/17062020.pdf', '2020/18062020.pdf', '2020/19062020.pdf', '2020/20062020.pdf', '2020/22062020.pdf', '2020/23062020.pdf', '2020/24062020.pdf', '2020/25062020.pdf', '2020/26062020.pdf', '2020/29062020.pdf', '2020/30062020.pdf', '2020/01072020.pdf', '2020/02072020.pdf', '2020/03072020.pdf', '2020/04072020.pdf', '2020/06072020.pdf', '2020/07072020.pdf', '2020/08072020.pdf', '2020/09072020.pdf', '2020/10072020.pdf', '2020/11072020.pdf', '2020/13072020.pdf', '2020/14072020.pdf']
len(list)

159

In [24]:
import camelot
import pandas as pd
import datetime

In [25]:
tables = camelot.read_pdf("01012020.pdf", pages="5, 6")
df = tables[0].df[10:]
df2 = tables[1].df[1:]
df = pd.concat([df,df2], axis=0)

In [26]:
df.columns =['S', 'NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']

In [27]:
df = df.drop(df.index[0])

In [28]:
df = df.drop(['S', 'ARRIVAL_IN_TONS', 'KG'], axis=1)

In [29]:
df['Date'] = "01012020"

In [30]:
df = df.reset_index(drop=True)

In [31]:
idx_start = df.index[df['NAME'] == 'ONION']
idx_end = df.index[df['NAME'] == 'G.ONION']
idx_start = idx_start[0]
idx_end = idx_end[0]
df = df[idx_start:idx_end]

In [32]:
df

,NAME,VARIETY,WEIGHT_IN_KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE,Date
79,ONION,,,,,,,,01012020
80,MAH,,40,KATTA,A,2200,2400,2300,01012020
81,,,40,KATTA,B,2000,2100,2050,01012020
82,MP/GUJ,,40,KATTA,A,2000,2200,2100,01012020
83,,,40,KATTA,B,1600,1800,1700,01012020
84,RAJ/HAR,,40,KATTA,A,2100,2400,2200,01012020
85,,,40,KATTA,B,1600,2000,1800,01012020
86,RAJ/HAR,GOLI,40,KATTA,,700,1200,1000,01012020
87,TURKEY/EGYPT,,40,KATTA,,1200,1600,1400,01012020
88,AFGHANISTAN,,40,KATTA,,1000,1100,1050,01012020

In [34]:
for item in list:
    print(item[5:])
    table = camelot.read_pdf(item[5:], pages="5, 6")
    df1 = table[0].df[1:]
    df3 = table[1].df[1:]
    df1 = pd.concat([df1,df3], axis=0)
    df1.columns =['S', 'NAME', 'ARRIVAL_IN_TONS', 'VARIETY', 'WEIGHT_IN_KG', 'KG', 'PACKING_SIZE', 'TYPE_OF_GRADE', 'MIN_PRICE', 'MAX_PRICE', 'MODAL_PRICE']
    df1 = df1.reset_index(drop=True)
    idx_start1 = df1.index[df1['NAME'] == 'ONION']
    idx_end1 = df1.index[df1['NAME'] == 'G.ONION']
    idx_start1 = idx_start1[0]
    idx_end1 = idx_end1[0]
    df1 = df1[idx_start:idx_end]
    df1 = df1.drop(df1.index[0])
    df1 = df1.drop(['ARRIVAL_IN_TONS', 'KG'], axis=1)
    df1['Date'] = item[5:13]
    df = pd.concat([df, df1], axis=0)

02012020.pdf
04012020.pdf
06012020.pdf
07012020.pdf
08012020.pdf
09012020.pdf
10012020.pdf
11012020.pdf
13012020.pdf
14012020.pdf
15012020.pdf
16012020.pdf
17012020.pdf
18012020.pdf
20012020.pdf
21012020.pdf
22012020.pdf
23012020.pdf
24012020.pdf
25012020.pdf
27012020.pdf
28012020.pdf
29012020.pdf
30012020.pdf
31012020.pdf
01022020.pdf
03022020.pdf
04022020.pdf
05022020.pdf
06022020.pdf
07022020.pdf
09022020.pdf
10022020.pdf
11022020.pdf
12022020.pdf
13022020.pdf
14022020.pdf
15022020.pdf
17022020.pdf
18022020.pdf
19022020.pdf
20022020.pdf
21022020.pdf
24022020.pdf
25022020.pdf
26022020.pdf
27022020.pdf
28022020.pdf
29022020.pdf
03032020.pdf
04032020.pdf
05032020.pdf

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
df.to_excel("bananas2020.xlsx")

,NAME,VARIETY,WEIGHT_IN_KG,PACKING_SIZE,TYPE_OF_GRADE,MIN_PRICE,MAX_PRICE,MODAL_PRICE,Date,S
87,HAR/UP/LOC,,1,BUN,,14,18,16,29022020,
88,,,,,,,,,29022020,50 MONGRA
80,,,1,LOOSE,B,8,14,12,03032020,
81,LEMON,,,,,,,,03032020,46
82,MAH/GUJ,,1,LOOSE,A,20,24,22,03032020,
83,,,1,LOOSE,B,14,18,16,03032020,
84,G.LOBHIYA,,,,,,,,03032020,47
85,W.B,,1,LOOSE,,30,40,35,03032020,
86,,,,,,,,,03032020,48 MANGO KERI
87,TN/CHENNAI,,1,LOOSE,,90,120,110,03032020,
88,,,,,,,,,03032020,49 MINT
80,,,1,LOOSE,B,14,18,16,04032020,
81,G.LOBHIYA,,,,,,,,04032020,47
82,W.B,,1,LOOSE,,25,35,30,04032020,
83,,,,,,,,,04032020,48 MANGO KERI
84,TN/CHENNAI,,1,LOOSE,,70,100,85,04032020,
85,,,,,,,,,04032020,49 MINT
86,HAR/UP/LOC,,1,BUN,,10,14,12,04032020,
87,,,,,,,,,04032020,50 MONGRA
88,UP,,1,LOOSE,,30,40,36,04032020,